package constants

const (
	HTTP_CLIENT_TIMEOUT_SECONDS = 30

	OGUN_CYCLE_FETCH_FREQUENCY_MINUTES = 5
	OGUN_MINIMUM_DIFF_TOLERANCE        = 1

	RPC_INIT_BATCH_SIZE            = 3
	OGUN_DELEGATE_FETCH_BATCH_SIZE = 50
	CONTRACT_FETCH_BATCH_SIZE      = 200

	LOG_LEVEL              = "LOG_LEVEL"
	LISTEN                 = "LISTEN"
	LISTEN_DEFAULT         = "127.0.0.1:3000"
	PRIVATE_LISTEN         = "PRIVATE_LISTEN"
	PRIVATE_LISTEN_DEFAULT = ""

	STORAGE_ROLLING = "rolling"
	STORAGE_ARCHIVE = "archive"
	STORED_CYCLES   = 20
)
